### ISSUE TITLE
Expose discovery websocket connection

### ISSUE THREAD

**Issue by dpaez** [RangerMauve/discovery-swarm-web#4]
Hi @RangerMauve would you consider a (simple, I guess) PR that exposes the discovery websocket connection? 

This can be useful for observability purposes like checking on the websocket state.

**Comment by RangerMauve** [comment]
Yeah, that's a great idea.

Maybe have an event get emitted with the discovery swarm stream client instance or whenever the new socket gets created?

**Comment by dpaez** [comment]
🤔Maybe the former is better. I've been playing with a dat viewer/inspector app and was using [this](https://github.com/RangerMauve/discovery-swarm-web/blob/master/index.js#L148) to get the websocket's readyState property.

**Comment by RangerMauve** [comment]
Yeah, whatever works for you!
