### ISSUE TITLE
discovery-swarm-web package installation problems

### ISSUE THREAD

**Issue by marcoippolito** [RangerMauve/discovery-swarm-web#9]
(base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn add discovery-swarm-web
    yarn add v1.22.4
    $ npx npm-force-resolutions
    npx: installed 5 in 0.753s
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix   
    package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, 
    remove package-lock.json.
    [1/4] Resolving packages...
    warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@1.2.0"
    [2/4] Fetching packages...
    warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/marco
    /.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity
    /node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic 
    behavior, skipping.
    info fsevents@2.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
    warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
    warning " > gun@0.2020.520" has unmet peer dependency "@gooddollar/react-native-webview-crypto@^0.*".
    warning " > gun@0.2020.520" has unmet peer dependency "bufferutil@^4.0.1".
    warning " > gun@0.2020.520" has unmet peer dependency "utf-8-validate@^5.0.2".
    warning "http-proxy-middleware > http-proxy > follow-redirects@1.12.0" has unmet peer dependency "debug@^3.0.0 || ^4.0.0".
    warning " > rxdb@9.3.0" has unmet peer dependency "rxjs@^6.5.4".
    warning "tiptap-extensions > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "y-protocols@^0.2.0".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-model@^1.7.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-state@^1.2.3".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-view@^1.9.10".
    [4/4] Building fresh packages...
    [1/2] ⢀ utp-native
    warning Error running install script for optional dependency: "/home/marco/webMatters/vueMatters/GGC/node_modules  
    /discovery-swarm/node_modules/utp-native: Command failed.
    Exit code: 1
    Command: node-gyp-build
    Arguments: 
    Directory: /home/marco/webMatters/vueMatters/GGC/node_modules/discovery-swarm/node_modules/utp-native
    Output:
    gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@14.3.0 | linux | x64
    gyp info find Python using Python version 3.7.4 found at \"/home/marco/anaconda3/bin/python\"
    gyp info spawn /home/marco/anaconda3/bin/python
    gyp info spawn args [
    gyp info spawn args   '/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp  
    /gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/webMatters/vueMatters/GGC/node_modules/discovery-swarm/node_modules/utp-native
    /build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/.cache/node-gyp/14.3.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/marco/.cache/node-gyp/14.3.0',
    gyp info spawn args   '-Dnode_gyp_dir=/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules/npm/node_modules/node-
    gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/marco/.cache/node-gyp/14.3.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/marco/webMatters/vueMatters/GGC/node_modules/discovery-
    swarm/node_modules/utp-native',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    make: Entering directory '/home/marco/webMatters/vueMatters/GGC/node_modules/discovery-swarm/node_modules/utp-
    native/build'
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_internal.o
    In file included from ../deps/libutp/utp_internal.cpp:33:
    ../deps/libutp/utp_internal.h: In constructor ‘UTPSocketKey::UTPSocketKey(const PackedSockAddr&, uint32)’:
    ../deps/libutp/utp_internal.h:79:32: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct   
    UTPSocketKey’; use assignment instead [-Wclass-memaccess]
       79 |   memset(this, 0, sizeof(*this));
          |                                ^
    ../deps/libutp/utp_internal.h:74:8: note: ‘struct UTPSocketKey’ declared here
       74 | struct UTPSocketKey {
          |        ^~~~~~~~~~~~
    ../deps/libutp/utp_internal.cpp: In function ‘size_t utp_process_incoming(UTPSocket*, const byte*, size_t, bool)’:
    ../deps/libutp/utp_internal.cpp:1970:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint32’    
    {aka ‘unsigned int’} [-Wsign-compare]
     1970 |   if (conn->mtu_probe_seq && seq == conn->mtu_probe_seq) {
          |                              ~~~~^~~~~~~~~~~~~~~~~~~~~~
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_utils.o
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_hash.o
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_callbacks.o
    In file included from ../deps/libutp/utp_callbacks.h:27,
                     from ../deps/libutp/utp_callbacks.cpp:25:
    ../deps/libutp/utp_internal.h: In constructor ‘UTPSocketKey::UTPSocketKey(const PackedSockAddr&, uint32)’:
    ../deps/libutp/utp_internal.h:79:32: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct    
    UTPSocketKey’; use assignment instead [-Wclass-memaccess]
       79 |   memset(this, 0, sizeof(*this));
          |                                ^
    ../deps/libutp/utp_internal.h:74:8: note: ‘struct UTPSocketKey’ declared here
       74 | struct UTPSocketKey {
          |        ^~~~~~~~~~~~
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_api.o
    In file included from ../deps/libutp/utp_api.cpp:26:
    ../deps/libutp/utp_internal.h: In constructor ‘UTPSocketKey::UTPSocketKey(const PackedSockAddr&, uint32)’:
    ../deps/libutp/utp_internal.h:79:32: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct     
    UTPSocketKey’; use assignment instead [-Wclass-memaccess]
       79 |   memset(this, 0, sizeof(*this));
          |                                ^
    ../deps/libutp/utp_internal.h:74:8: note: ‘struct UTPSocketKey’ declared here
      74 | struct UTPSocketKey {
          |        ^~~~~~~~~~~~
      CXX(target) Release/obj.target/libutp/deps/libutp/utp_packedsockaddr.o
      AR(target) Release/obj.target/deps/utp.a
      COPY Release/utp.a
      CXX(target) Release/obj.target/utp/src/utp_uv.o
    In file included from ../src/utp_uv.cc:2:
    ../../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
    ../../../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void  
    (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
          |                                                              ^
    ../src/utp_uv.cc: At global scope:
    ../src/utp_uv.cc:219:1: warning: ‘uint64 on_utp_schedule_ack(utp_callback_arguments*)’ defined but not used [-Wunused- 
    function]
      219 | on_utp_schedule_ack (utp_callback_arguments *a) {
          | ^~~~~~~~~~~~~~~~~~~
      CXX(target) Release/obj.target/utp/src/socket_wrap.o
    In file included from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    ../../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
    ../../../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void       
    (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
          |                                                              ^
    ../src/socket_wrap.cc: In member function ‘int SocketWrap::Drain()’:
    ../src/socket_wrap.cc:69:40: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, 
    v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       69 |       this->on_drain->Call(ctx, 0, NULL);
          |                                        ^
    In file included from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    ../../../../nan/nan.h:1720:3: note: declared here
     1720 |   Call(v8::Local<v8::Object> target
          |   ^~~~
    ../src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE    
    SocketWrap::Context(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/socket_wrap.cc:99:45: error: no matching function for call to ‘v8::Value::ToObject()’
       99 |   Local<Object> context = info[0]->ToObject();
          |                                             ^
    In file included from /home/marco/.cache/node-gyp/14.3.0/include/node/node.h:67,
                     from ../../../../nan/nan.h:56,
                     from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:2819:44: note: candidate: ‘v8::MaybeLocal<v8::Object>    
    v8::Value::ToObject(v8::Local<v8::Context>) const’
     2819 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
          |                                            ^~~~~~~~
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:2819:44: note:   candidate expects 1 argument, 0 provided
    . ./src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE    
    SocketWrap::Write(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/socket_wrap.cc:113:43: error: no matching function for call to ‘v8::Value::ToObject()’
      113 |   Local<Value> buffer = info[0]->ToObject();
          |                                           ^
    In file included from /home/marco/.cache/node-gyp/14.3.0/include/node/node.h:67,
                     from ../../../../nan/nan.h:56,
                     from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:2819:44: note: candidate: ‘v8::MaybeLocal<v8::Object>  
    v8::Value::ToObject(v8::Local<v8::Context>) const’
     2819 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
          |                                            ^~~~~~~~
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:2819:44: note:   candidate expects 1 argument, 0 provided
    ../src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE  
     SocketWrap::Writev(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/socket_wrap.cc:141:49: error: no matching function for call to ‘v8::Array::Get(uint32_t&)’
      141 |     Local<Value> buffer = Nan::Get(writes->Get(i)->ToObject(), chunk).ToLocalChecked();
          |                                                 ^
    In file included from /home/marco/.cache/node-gyp/14.3.0/include/node/node.h:67,
                     from ../../../../nan/nan.h:56,
                     from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note: candidate: ‘v8::MaybeLocal<v8::Value>  
    v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
     3686 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
          |                                           ^~~
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note:   candidate expects 2 arguments, 1 provided
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note: candidate: ‘v8::MaybeLocal<v8::Value>   
    v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
     3689 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
          |                                           ^~~
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note:   candidate expects 2 arguments, 1 provided
    ../src/socket_wrap.cc: In static member function ‘static v8::Local<v8::Value> SocketWrap::NewInstance()’:
    ../src/socket_wrap.cc:243:62: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
      243 |   instance = Nan::NewInstance(constructorHandle->GetFunction()).ToLocalChecked();
          |                                                              ^
    In file included from /home/marco/.cache/node-gyp/14.3.0/include/node/node.h:67,
                     from ../../../../nan/nan.h:56,
                     from ../src/socket_wrap.h:4,
                     from ../src/socket_wrap.cc:1:
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note: candidate: ‘v8::MaybeLocal<v8::Function>        
    v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
     6404 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
          |                                              ^~~~~~~~~~~
    /home/marco/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note:   candidate expects 1 argument, 0 provided
    utp.target.mk:121: recipe for target 'Release/obj.target/utp/src/socket_wrap.o' failed
    make: *** [Release/obj.target/utp/src/socket_wrap.o] Error 1
    make: Leaving directory '/home/marco/webMatters/vueMatters/GGC/node_modules/discovery-swarm/node_modules/utp-
    native/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/marco/.nvm/versions/node/v14.3.0/lib/node_modules/npm/node_modules
    /node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    gyp ERR! System Linux 5.3.0-62-generic
    gyp ERR! command \"/home/marco/.nvm/versions/node/v14.3.0/bin/node\" \"/home/marco/.nvm/versions/node/v14.3.0/
     lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
    gyp ERR! cwd /home/marco/webMatters/vueMatters/GGC/node_modules/discovery-swarm/node_modules/utp-native
    gyp ERR! node -v v14.3.0
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok"
    success Saved lockfile.
    success Saved 17 new dependencies.
    info Direct dependencies
    └─ discovery-swarm-web@2.0.0
    info All dependencies
    ├─ circular-append-file@1.0.1
    ├─ connections@1.4.2
     ├─ dat-encoding@5.0.1
    ├─ dat-swarm-defaults@1.0.2
    ├─ discovery-channel@5.5.1
    ├─ discovery-swarm-stream@2.1.1
    ├─ discovery-swarm-web@2.0.0
    ├─ discovery-swarm@5.1.4
    ├─ dns-discovery@6.2.3
    ├─ dns-socket@3.0.0
    ├─ hyperdiscovery@9.0.2
    ├─ length-prefixed-stream@1.6.0
    ├─ mutexify@1.3.0
    ├─ network-address@1.1.2
    ├─ sodium-javascript@0.5.6
    ├─ sorted-indexof@1.0.0
    └─ to-buffer@1.1.1
    $ electron-builder install-app-deps
      • electron-builder  version=22.7.0
      • rebuilding native dependencies  dependencies=abstract-socket@2.1.1, bufferutil@4.0.1, canvas@2.6.1, fd-lock@1.1.1,    
    sodium-native@3.2.0, utf-8-validate@5.0.2, utp-native@2.2.1, websocket@1.0.31, sodium-native@2.4.9
                                        platform=linux
                                        arch=x64
      • rebuilding native dependency  name=bufferutil version=4.0.1
      • rebuilding native dependency  name=abstract-socket version=2.1.1
      • rebuilding native dependency  name=canvas version=2.6.1
      • rebuilding native dependency  name=fd-lock version=1.1.1
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=utf-8-validate version=5.0.2
      • rebuilding native dependency  name=utp-native version=2.2.1
      • rebuilding native dependency  name=websocket version=1.0.31
      • rebuilding native dependency  name=sodium-native version=2.4.9
    Done in 102.43s.

I then removed discovery-swarm-web and installed node-gyp alone:

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn remove discovery-swarm-web
    yarn remove v1.22.4
    [1/2] Removing module discovery-swarm-web...
    [2/2] Regenerating lockfile and installing missing dependencies...
    success Uninstalled packages.

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn add node-gyp
    yarn add v1.22.4
    $ npx npm-force-resolutions
    npx: installed 5 in 0.75s
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix 
    package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning,    
    remove package-lock.json.
    [1/4] Resolving packages...
    warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@1.2.0"
    [2/4] Fetching packages...
    warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/marco
    /.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity   
    /node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic 
    behavior, skipping.
    info fsevents@2.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
    warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
    warning " > gun@0.2020.520" has unmet peer dependency "@gooddollar/react-native-webview-crypto@^0.*".
    warning " > gun@0.2020.520" has unmet peer dependency "bufferutil@^4.0.1".
    warning " > gun@0.2020.520" has unmet peer dependency "utf-8-validate@^5.0.2".
    warning "http-proxy-middleware > http-proxy > follow-redirects@1.12.0" has unmet peer dependency "debug@^3.0.0 || ^4.0.0".
    warning " > rxdb@9.3.0" has unmet peer dependency "rxjs@^6.5.4".
    warning "tiptap-extensions > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "y-protocols@^0.2.0".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-model@^1.7.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-state@^1.2.3".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-view@^1.9.10".
    [4/4] Building fresh packages...

    success Saved 1 new dependency.
    info Direct dependencies
    └─ node-gyp@7.0.0
    info All dependencies
    └─ node-gyp@7.0.0
    $ electron-builder install-app-deps
      • electron-builder  version=22.7.0
      • rebuilding native dependencies  dependencies=abstract-socket@2.1.1, bufferutil@4.0.1, canvas@2.6.1, fd-lock@1.1.1,  
    sodium-native@3.2.0, utf-8-validate@5.0.2, utp-native@2.2.1, websocket@1.0.31
                                        platform=linux
                                        arch=x64
      • rebuilding native dependency  name=bufferutil version=4.0.1
      • rebuilding native dependency  name=abstract-socket version=2.1.1
      • rebuilding native dependency  name=canvas version=2.6.1
      • rebuilding native dependency  name=fd-lock version=1.1.1
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=utf-8-validate version=5.0.2
      • rebuilding native dependency  name=utp-native version=2.2.1
      • rebuilding native dependency  name=websocket version=1.0.31
    Done in 18.35s.

But adding again discovery-swarm-web package gives the above errors

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
      Browsers:
        Chrome: 84.0.4147.89
        Firefox: 78.0.2
      npmGlobalPackages:
        @vue/cli: 4.4.4

**Comment by RangerMauve** [comment]
Node-gyp should be installed globally rather than at the project level.

Also, I think this might be an issue with the utp-native module not compiling on node 14, so it might be worth it to open an issue there. 😁 https://github.com/mafintosh/utp-native

**Comment by marcoippolito** [comment]
@RangerMauve I guess you are right. It should be a problem of utp-native module with node 14.
I opened an issue: https://github.com/mafintosh/utp-native/issues/36

**Comment by RangerMauve** [comment]
Feel free to submit a pull request that updates the dependency once they fix it. 😁

In the meantime, you can try using Node@12 using nvm or something. I've had good results with it so far

**Comment by marcoippolito** [comment]
@RangerMauve  utp-native owner says that he doesn't know enough about my environment to help me with that.

I tried to install discovery-swarm-web with v.12 of node.js but still get the same errors: 
[discovery-swarm-web-node12-InstallationProblems.txt](https://github.com/RangerMauve/discovery-swarm-web/files/4971564/discovery-swarm-web-node12-InstallationProblems.txt)


After removing discovery-swarm-web and node-gyp, the installation of utp-native and of node-gyp went fine this time: 
[utp-nativeInstallationOK.txt](https://github.com/RangerMauve/discovery-swarm-web/files/4972251/utp-nativeInstallationOK.txt).

But after correctly installing utp-native and node-gyp, installing discovery-swarm-web has the same problems:
[discovery-swarm-web-node12-InstallationProblemsAfterCorrectlyInstallingUtpNativeNodeGyp.txt](https://github.com/RangerMauve/discovery-swarm-web/files/4972286/discovery-swarm-web-node12-InstallationProblemsAfterCorrectlyInstallingUtpNativeNodeGyp.txt)

**Comment by RangerMauve** [comment]
@marcoippolito Have you considered using `hyperswarm-web` in the meantime? It uses a newer version of utp-native which might help.
